base/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import CreateAccount, WorkoutCreate, WorkoutDelete, WorkoutList, WorkoutDetails, WorkoutUpdate, CustomLoginView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', WorkoutList.as_view(), name='workouts'),
    path('register/', CreateAccount.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(next_page = 'login'), name='logout'),
    path('workout/<int:pk>/', WorkoutDetails.as_view(), name = 'workout'),
    path('create-workout', WorkoutCreate.as_view(), name='create-workout'),
    path('update-workout/<int:pk>/', WorkoutUpdate.as_view(), name = 'update-workout'),
    path('delete-workout/<int:pk>/', WorkoutDelete.as_view(), name = 'delete-workout'),
]

running_workouts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.db.models.deletion import CASCADE, RestrictedError
from django.contrib.auth.models import User


RACE_CHOICES = {
    ('800m', '800m'),
    ('mile', '1600m'),
    ('5k', '5k'),
    ('half-marathon', 'Half Marathon'),
    ('marathon', 'Marathon'),
}
# Create your models here.
class Workout(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    instructions = models.TextField(null = True, blank = True)
    mileage = models.DecimalField(decimal_places = 1, max_digits = 3 ,null = True, blank = True)
    race_type =models.CharField(max_length = 100, choices = RACE_CHOICES, default = '5k')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['race_type']
    
    

base/views.py
from django.shortcuts import render
from django.urls.base import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.db.models import Sum

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from.models import Workout

class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('workouts')




# Create your views here.
class WorkoutList(LoginRequiredMixin, ListView):
    model = Workout
    context_object_name = 'workouts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workouts'] = context['workouts'].filter(user = self.request.user)
        return context


class WorkoutDetails(DetailView):
    model = Workout
    context_object_name = 'workout'
    template_name = 'base/workout.html'


class WorkoutCreate(LoginRequiredMixin, CreateView):
    model = Workout
    fields = ['title', 'instructions','mileage', 'race_type']
    success_url = reverse_lazy('workouts')
    template_name = 'base/create-workout.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(WorkoutCreate, self).form_valid(form)

class WorkoutUpdate(LoginRequiredMixin, UpdateView):
    model = Workout
    fields = ['title', 'instructions','mileage', 'race_type']
    success_url = reverse_lazy('workouts')
    template_name = 'base/update-workout.html'

class WorkoutDelete(LoginRequiredMixin, DeleteView):
    model = Workout
    template_name= 'base/delete-workout.html'
    success_url = reverse_lazy('workouts')

class CreateAccount(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('workouts')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(CreateAccount, self).form_valid(form)


    

base/templates/base/create-workout.html
{% extends 'base/main.html' %}
{% block content %}

<div class ="header-bar">
    <h3>Create a workout</h3>
    <a href='{% url 'workouts' %}'>&#8592; Back</a>

</div>

<div class = "card-body">
<form method = "POST" action="">
    {%csrf_token%}
    {{form.as_p}}
    <input class = "button" type= "submit" value="Create">
</form>
</div>

{% endblock content %}

base/templates/base/delete-workout.html
{% extends 'base/main.html' %}
{% block content %}

<div class = "header-bar">
    <a href='{%url 'workouts' %}'>&#8592;Back</a>
</div>
<div class = "card-body">
<form method="POST">
    {% csrf_token %}
    <p style = "color: #2bbc8a">Are you sure you want to delete this workout?</p>
    <input class = "button" type ="submit" value = "Delete">
</form>
</div>

{% endblock content %}

base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}

<div class = "header-bar">
    <h1>Login</h1>
</div>

<div class= "card-body">
<form method = "POST">
    {%csrf_token %}
    {{form.as_p}}
    <input class = "button" type = "submit" value = "Login">
</form>

<p>Don't have an account? <a style = "text-decoration: none; color: #2bbc8a" href='{% url 'register' %}'> Register</a></p>

</div>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Workout Tracker</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100&display=swap" rel="stylesheet"> 

    <style>
        body {
            background-color: #1d1f21;
            font-family: "jetBrains", monospace;
            font-weight: 400;
            padding-top: 50px;
            color: #c9cacc;
        }

        h1,h2,h3,h4,h5,h6{
            font-family: "jetBrains", monospace;
            color: #2bbc8a;
        }

        .container{
            max-width: 600px;
            margin: auto;
        }

        .header-bar {
            display: flex;
            justify-content: space-between;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            color: #c9cacc;
        }

        .header-bar a {
            text-decoration: none;
            color: #c9cacc;
        }

        .workouts-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            background-color: #1d1f21;
            border-top: 1px solid rgb(226, 226, 226);
        }

        .workout-title{
            display: flex;
        }

        .workout-title a {
            text-decoration :none;
            color: #c9cacc;
            margin-left: 10px;

        }

        .delete-link {
            text-decoration: none;
            font-weight: 900;
            color: #c9cacc;
            font-size: 22px;
            line-height: 0px;

        }

        #add-link {
            color: #2bbc8a;
            font-size: 14px;
            cursor: pointer;
            padding-top: 20px;
            margin-bottom: 20px;
            text-decoration: underline;
           text-align: right;

        }

        input[type=text],
        #id_race_type,
        input[type=number],
        input[type=password],
        textarea{
            border: 1px solid #c9cacc;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
            background-color: #c9cacc;
        }

        .button {
            border: 1px solid #c9cacc;
            background-color: #c9cacc;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }

        .card-body {
            padding: 20px;
        }

    </style>
</head>
<body>
    <div class = "container">
        {%block content%}

        {% endblock content %}


    </div>
</body>
</html>

base/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
<h1>Register</h1>
</div>

<div class = "card-body">
<form method = "POST">
    {%csrf_token %}
    {{form.as_p}}
    <input class = "button" type = "submit" value = "Register">
</form>

<p>Already have an account? <a style = "text-decoration: none; color: #2bbc8a" href='{% url 'login' %}'>Login</a></p>
</div>

{% endblock content %}

base/templates/base/update-workout.html
{% extends 'base/main.html' %}
{% block content %}

<div class ="header-bar">
    <h3>Edit "{{workout}}"</h3>
    <a style = "text-decoration: underline" href='{% url 'workouts' %}'>&#8592; Back</a>

</div>


<div class="card-body">
<form method = "POST" action="">
    {%csrf_token%}
    {{form.as_p}}
    <input class = "button" type= "submit" value="Update">

</div>

{% endblock content %}

base/templates/base/workout.html
<h3>Workout: {{workout}}</h3>

base/templates/base/workout_list.html
{% extends 'base/main.html' %}
{% block content %}


<div class = "header-bar">
    <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style= "margin: 0; color: #c9cacc; padding-bottom: 10px"> welcome to your running log</h3>

        <a id="add-link" href = '{% url 'create-workout'  %}'>Create a workout</a> 
    </div>

        {% if request.user.is_authenticated %}
    <a href='{%url 'logout' %}'>Logout</a>

    {% else %}
    <a href='{%url 'login' %}'>Login</a>
    {% endif %}

    

</div>
<div class="workout-items-wrapper">
    {% for workout in workouts %}
    <div class = "workouts-wrapper">
        <div class="workout-title">
            <a href = '{% url 'update-workout' workout.id %}'>{{workout}}</a>
        </div>
        <a class ='delete-link' href = '{% url 'delete-workout' workout.id %}'>&#215;</a>
    </div>
    {% empty %}
    <h3 style = "color: #c9cacc; padding:10px; border-top: 1px solid #c9cacc" >Please Create a Workout</h3>
    {% endfor %}
</div>


<!-- <table>
    <tr>
        <th>Workout</th>
        <th>Mileage</th>
        <th>Race</th>
        <th></th>
        <th></th>
    </tr>
    {% for workout in workouts %}
    <tr>
        <td>{{workout.title}}</td>
        <td>{{workout.mileage}}</td>
        <td>{{workout.race_type}}</td>
        <td><a href = '{% url 'update-workout' workout.id %}'>Edit</a></td>
        <td><a href = '{% url 'delete-workout' workout.id %}'>Delete</a></td>
    </tr>

    {% empty %}
        <h3>Please Create a Workout</h3>
    {% endfor %}
    <tr>
    </tr>
</table>

-->

{% endblock content %}